### ISSUE TITLE
Question: GameMaker: HTML5

### ISSUE THREAD

**Issue by joelb-2011** [KuromeSan/chovy-gm#23]
You can also make PSP games using GameMaker: HTML5 or just with Game Maker 8.1?  Game Maker: HTML5 is similar to GameMaker 8.1, only export for HTML5 is added.  Will you be able to play games there?

**Comment by KuromeSan** [comment]
you cannot making PSP games using GameMaker: HTML5. unless you have YOYO_DEV_ENABLE & YOYO_INTERNAL_ENABLE flag set. btw, this compiler works best with GameMaker HTML5 games as this is the latest runnner.
