### ISSUE TITLE
Help with directory

### ISSUE THREAD

**Issue by TeamCS1** [KuromeSan/chovy-gm#25]
Alright so I've created the exe for the game along with the icon0 and pic0 and it looks all okay. 

When clicking the build iso button the program crashes with this error code:

 "An unhandled exception of type 'System.IO.DirectoryNotFoundException' occurred in mscorlib.dll

Additional information: Could not find a part of the path 'C:\Users\tabee\Desktop\FalloutPortable\chovy-gm-master\bin\Release\RUNNER'."

I'd assume it'd generate the folder itself but there is no runner folder. I have the eboot but not sure where to place it. (I've tried placing the eboot inside a RUNNER folder I have created, but still same issue).

Thank you.

**Comment by LAZERPOINT** [comment]
ok, but were do i open the app itself

**Comment by KuromeSan** [comment]
did you compile it from source? you have to copy the RUNNER folder from the releases zip file !
