### ISSUE TITLE
Joystick Mapping

### ISSUE THREAD

**Issue by retrosprite** [KuromeSan/chovy-gm#5]
Any support for the PSP's joystick?

**Comment by KuromeSan** [comment]
Its mapped to mouse.

**Comment by retrosprite** [comment]
Which means it would only be useful as a cursor.

**Comment by KuromeSan** [comment]
Thats just how YoYoGames did it- there isnt anything i can do about it

In theroy you can use it for more than just a cursor-
think minecraft- they use *just the cursor* to look around- by constatnly setting the mouse back to one position and seeing how far it moved from that position on each frame you can mimick a 'joystick' 

and in theroy you can do this on GMPSP too-
you have `window_mouse_set(x,y)` and `window_mouse_get_y()` `window_mouse_get_x()`
so you could try do somthing simular

no idea if these functions work on PSP though.

**Comment by retrosprite** [comment]
> Thats just how YoYoGames did it- there isnt anything i can do about it
> 
> In theroy you can use it for more than just a cursor-
> think minecraft- they use _just the cursor_ to look around- by constantly setting the mouse back to one position and seeing how far it moved from that position on each frame you can mimick a 'joystick'
> 
> and in theroy you can do this on GM too-
> you have `window_mouse_set(x,y)` and `window_mouse_get_y()` `window_mouse_get_x()`
> so you could try do somthing simular
> 
> no idea if these functions work on PSP though.

Yeah I attempted your theory earlier after your first reply and it did work on PC but on the PSP when I used draw_self() it didn't boot so I didn't find out if it worked on there. I gave up on it after that.

**Comment by KuromeSan** [comment]
i remember when we first tried it out we couldnt get `draw_self()` to work wasnt aware even with the correct formatting of the .psp it still doesnt

anyway `draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha)` is the same as `draw_self()`

**Comment by retrosprite** [comment]
> i remember when we first tried it out we couldnt get `draw_self()` to work wasnt aware even with the correct fixes made to the .psp builder it still doesnt..
> 
> anyway `draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha)` is the same as `draw_self()`
> 
> this is all just limitations of the PSP GameMaker 8.1 runner anyway- all i can fix is file format issues ..
> if you want a more complete verison of gamemaker on a portable console maybe look into the PSVita xD

I sold my Vita a couple years ago which is why I'm messing with this instead. Can't really justify buying another one just for messing with GameMaker on it although it is tempting lol.
