### ISSUE TITLE
Trying to read or write a file seems to be freezing the game

### ISSUE THREAD

**Issue by mejeve** [KuromeSan/chovy-gm#8]
I have a game which is running a few filed read and write functions.
For example
```
//Eg.1.Checking if file exists
file_exists("tntbf.sav")

//Eg.2 Opening a file
load = file_text_open_read("tntbf.sav")

//Eg.3 Writing to a file
save = file_text_open_write("tntbf.sav")
file_text_write_string(save,"Save Data.")
file_text_writeln(save)
```
As soon as this happens the game is freezing. So, I had to comment out the file writing part.
Is there supposed to be a safe/allowed location I'm supposed to write to or is file access not permitted on the PSP or the GML interpreter?

How do I save stuff and track user progress? Is there a PSP API avaialable for saving games?

**Comment by KuromeSan** [comment]
maybe you have to specify the whole path- like ms0:/PSP/SAVEDATA/WHATEVER

**Comment by mejeve** [comment]
That'd be helpful(Checking how Karoshi does this). Since I don't even know how the PSP handles save files. I'm not really sure if it's as easy as writing files to the save path. Maybe it has an API or something.
Thanks!

**Comment by KuromeSan** [comment]
i know how it works on the vita lol

**Comment by KuromeSan** [comment]
` 	   save_data +  if global.wentintolevelselect=0

{

ini_open("data.ini")

ini_write_real("Save Data","Level",min(max(global.levelnum,1),50))
ini_write_real("Save Data","Coins",global.coins)
if variable_global_exists("lastroom") ini_write_real("Save Data","Room",global.lastroom)
else ini_write_real("Save Data","Room",1)
ini_write_real("Save Data","Music",global.playmusic)
ini_write_real("Save Data","Sound",global.playsound)
ini_write_real("Save Data","Unlock1",global.unlocked1)
ini_write_real("Save Data","Unlock2",global.unlocked2)

ini_close()

}
 	   load_data È  ini_open("data.ini")

global.level_continue = ini_read_real("Save Data","Level",-1)
global.coins_continue = ini_read_real("Save Data","Coins",0)
global.room_continue = ini_read_real("Save Data","Room",0)
global.playmusic = ini_read_real("Save Data","Music",1)
global.playsound = ini_read_real("Save Data","Sound",1)
global.unlocked1 = ini_read_real("Save Data","Unlock1",0)
global.unlocked2 = ini_read_real("Save Data","Unlock2",0)

ini_close()
`

**Comment by mejeve** [comment]
Is there a way to check if this the first time creating the ini? Does opening the ini without creating it create an empty file or an exception/error?

**Comment by KuromeSan** [comment]
no- its likely an encrypted archive or something.

you can stil open ("data.ini") but the actural file written to the memory stick is an encrypted "SECURE.BIN" file for some reason

**Comment by mejeve** [comment]
Looks like the ini is created as soon as you use the open function if it doesn't already exist.
From the `docs

>https://docs.yoyogames.com/source/dadiospice/002_reference/file%20handling/ini%20files/index.html
>This opens an ini_file for reading and/writing. If the ini_file does not exist at the location you are checking, GameMaker: Studio may create one, but only if you write data to it. If you have only read information from the ini file, then the default values for the read function will be returned, but the ini file will not actually be created.

**Comment by KuromeSan** [comment]
there is no actural "INI" saved in this verison it seems to just use those functions to create some encrypted archive file .. but you can still use it as if its an INI.
